[package]
name = "rust-embed"
version = "4.4.0"
description = "Rust Custom Derive Macro which loads files into the rust binary at compile time during release and loads the file from the fs during dev"
readme = "readme.md"
documentation = "https://docs.rs/rust-embed"
repository = "https://github.com/pyros2097/rust-embed"
license = "MIT"
keywords = ["http", "rocket", "static", "web", "server"]
categories = ["web-programming::http-server"]
authors = ["pyros2097 <pyros2097@gmail.com>"]

[dependencies]
walkdir = "2.2.8"
rust-embed-impl = { version = "4.4.0", path = "impl"}

actix-web = { version = "0.7", optional = true }
mime_guess = { version = "2.0.0-alpha.6", optional = true }
warp = { version = "0.1", optional = true }
rocket = { version = "0.4.1", optional = true }

[features]
debug-embed = ["rust-embed-impl/debug-embed"]
interpolate-folder-path = ["rust-embed-impl/interpolate-folder-path"]
nightly = ["rocket"]
actix = ["actix-web", "mime_guess"]
warp-ex = ["warp", "mime_guess"]

[badges]
appveyor = { repository = "pyros2097/rust-embed" }
travis-ci = { repository = "pyros2097/rust-embed" }
is-it-maintained-issue-resolution = { repository = "pyros2097/rust-embed" }
is-it-maintained-open-issues = { repository = "pyros2097/rust-embed" }
maintenance = { status = "passively-maintained" }
