[package]
name = "rust-embed"
version = "4.0.0"
description = "Rust Custom Derive Macro which loads files into the rust binary at compile time during release and loads the file from the fs during dev"
readme = "readme.md"
documentation = "https://docs.rs/rust-embed"
repository = "https://github.com/pyros2097/rust-embed"
license = "MIT"
keywords = ["http", "rocket", "static", "web", "server"]
categories = ["web-programming::http-server"]
authors = ["pyros2097 <pyros2097@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
walkdir = "2.1.4"

actix-web = { version = "0.7", optional = true }
mime_guess = { version = "2.0.0-alpha.6", optional = true }

rocket = { version = "0.3.6", optional = true }
rocket_codegen = { version = "0.3.6", optional = true }
rocket_contrib = { version = "0.3.6", optional = true }

[features]
default = ["binary"]
binary = []
nightly = ["rocket", "rocket_codegen", "rocket_contrib"]
actix = ["actix-web", "mime_guess"]

[badges]
appveyor = { repository = "pyros2097/rust-embed" }
travis-ci = { repository = "pyros2097/rust-embed" }
is-it-maintained-issue-resolution = { repository = "pyros2097/rust-embed" }
is-it-maintained-open-issues = { repository = "pyros2097/rust-embed" }
maintenance = { status = "passively-maintained" }
