[package]
name = "rust-embed-utils"
version = "5.0.0"
description = "Utilities for rust-embed"
readme = "readme.md"
documentation = "https://docs.rs/rust-embed"
repository = "https://github.com/pyros2097/rust-embed"
license = "MIT"
keywords = ["http", "rocket", "static", "web", "server"]
categories = ["web-programming::http-server"]
authors = ["pyros2097 <pyros2097@gmail.com>"]

[dependencies]
walkdir = "2.2.9"

[features]
debug-embed = []
